version: "3.9"

services:
  web:
    build:
      context: .
      dockerfile: node.dockerfile
    image: my_web_sample
    container_name: my_web_sample
    ports:
      - "3000:3000"
    networks:
      app_net:
        ipv4_address: 192.168.229.26
    volumes:
      - ../app:/home/my_web_sample/app
    tty: true
  db:
    image: mysql:8.0.33-oracle
    container_name: my_web_sample_mysql
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: yes
      MYSQL_USER: my_web_sample
      MYSQL_PASSWORD: my_web_sample
      MYSQL_DATABASE: my_web_sample
    ports:
      - "3306:3306"
    networks:
      app_net:
        ipv4_address: 192.168.229.27
    volumes:
      - ../mysql:/var/lib/mysql
  smtp:
    image: schickling/mailcatcher
    ports:
      - "1080:1080"
      - "1025:1025"
    networks:
      app_net:
        ipv4_address: 192.168.229.28

networks:
  app_net:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 192.168.229.25/24
