version: "3.9"

services:
  terraform:
    build: .
    container_name: ${CONTAINER_NAME?err}
    ports:
      - "1111:1111"
    networks:
      app_net:
        ipv4_address: 192.23.2.130
    volumes:
      - ../app:/home/terraform/app
    tty: true
    privileged: true
  localstack:
    container_name: "${LOCALSTACK_DOCKER_NAME-localstack_main}"
    image: localstack/localstack
    ports:
      - "127.0.0.1:4566:4566" # LocalStack Gateway
      - "127.0.0.1:4510-4559:4510-4559" # external services port range
    environment:
      - DEBUG=${DEBUG-}
      - DOCKER_HOST=unix:///var/run/docker.sock
    networks:
      app_net:
        ipv4_address: 192.23.2.129
    volumes:
      - "${LOCALSTACK_VOLUME_DIR:-../localstack}:/var/lib/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"
networks:
  app_net:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 192.23.2.128/24
